
POST http://localhost:9000/api/v1/auth/register HTTP/1.1
content-type: application/json

{
    "username": "arifin33",
    "password": "arifin123#",
    "email": "arifin@test.com"
}

###

POST http://localhost:9000/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "username": "",
    "password": ""
}
