
POST http://localhost:9000/api/v1/auth/register HTTP/1.1
content-type: application/json

{
    "fullname": "User1",
    "username": "user1",
    "password": "user123#",
    "email": "user@test.com"
}

###

POST http://localhost:9000/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "username": "",
    "password": ""
}
